name: Deploy Javadoc

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy JavaDoc 🚀
        uses: MathieuSoysal/Javadoc-publisher.yml@v2.3.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: javadoc
          java-version: 21
          project: gradle
          target-folder: ${{ github.event.release.tag_name }}
          custom-command: chmod +x ./gradlew && ./gradlew javadoc
