name: Deploy Javadoc

on:
  push:
    branches:
      - 1.*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=branches/${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Deploy JavaDoc 🚀
        uses: MathieuSoysal/Javadoc-publisher.yml@v2.3.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: javadoc
          java-version: 21
          project: gradle
          target-folder: ${{ steps.extract_branch.outputs.branch }}
          custom-command: chmod +x ./gradlew && ./gradlew javadoc
